import { useEffect, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, Brain, ChevronDown, ChevronRight, Circle, CircleDot, Fingerprint, Focus, Maximize2, MousePointer2, Orbit, Pause, Play, RotateCcw, Scan, SlidersHorizontal, Sun, Volume2, VolumeX, Waves, Wind } from 'lucide-react';
import { useStore } from '../store';
import { manualStimulus, descriptions } from '../runtime';
import { enableAudio } from '../audio';
import { MODULES } from '../config';
import { MosquitoMark } from './Icon';
import { Drawer } from './Drawer';
const behaviorText = {resting:'Quietly plotting.',sensing:'Something in the air.',approaching:'Following a warm feeling.',hovering:'Too much on her mind.',feeding:'Just a little closer.',startled:'Absolutely not.',recovering:'Collecting herself.'};
export function Interface() {
  const s=useStore(),[now,setNow]=useState(Date.now()),[tapNotice,setTapNotice]=useState(false);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.ctrlKey||e.metaKey||e.altKey||['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement).tagName)||(e.target as HTMLElement).isContentEditable)return;const state=useStore.getState();if(state.drawer)return;
    switch(e.key.toLowerCase()){case ' ':if((e.target as HTMLElement).tagName==='BUTTON')return;e.preventDefault();state.patch({paused:!state.paused});break;case 'c':state.patch({cinema:!state.cinema});break;case 'r':state.patch({cameraReset:state.cameraReset+1});break;case 'l':state.patch({tool:state.tool==='lure'?'orbit':'lure'});if(state.tool!=='lure')manualStimulus('attraction');break;case 'g':manualStimulus('tap');break;case 'p':manualStimulus('co2');break;case 's':manualStimulus('shadow');break;case '1':state.patch({view:'exhibit'});break;case '2':state.patch({view:'brain'});break;case '3':state.patch({view:'body'});break;case 'escape':state.patch({cinema:false,tool:'orbit',selectedModule:null});break;}
  };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  const activity=s.modules.reduce((a,b)=>a+b,0)/8;
  const explained=s.latest??s.reaction;
  const source=explained?.source||s.feed.mode;
  const age=s.feed.lastTrade?Math.max(0,Math.floor((now-s.feed.lastTrade)/1000)):null;
  const heartbeat=s.feed.lastHeartbeat&&now-s.feed.lastHeartbeat<6500;
  const chart=s.activityHistory.map((x,i)=>`${i*4.6},${37-Math.min(1,x)*33}`).join(' ');
  const traceMatches = s.trace?.id===s.latest?.id;
  const traceStages=[traceMatches&&s.trace?.sensoryAt!==null,traceMatches&&s.trace?.integrationAt!==null,traceMatches&&s.trace?.motorAt!==null,traceMatches&&s.trace?.motorAt!==null&&s.behavior!=='resting'];
  const selected=s.hoveredModule??s.selectedModule;
  const tap=()=>{if(!manualStimulus('tap')){setTapNotice(true);setTimeout(()=>setTapNotice(false),1800);}};
  return <div className={`interface ${s.cinema?'cinema':''}`}>
    <header className="topbar"><a href={import.meta.env.BASE_URL} className="brand" aria-label="MOSQUITO home"><MosquitoMark size={30}/><span>MOSQUITO<span className="brand-dot">°</span></span></a><div className="topbar-center"><span className="tiny-cross">+</span> A LIVING INTERNET EXPERIMENT <span className="tiny-cross">+</span></div><nav><button className="nav-button about-button" onClick={()=>s.patch({drawer:'about'})}>The experiment <ArrowUpRight size={13}/></button><span className="nav-divider"/><button className={`nav-button sound-button ${s.audio?'active':''}`} onClick={enableAudio} aria-label={s.audio?'Mute sound':'Enable sound'}>{s.audio?<Volume2 size={15}/>:<VolumeX size={15}/>}<span>Sound {s.audio?'on':'off'}</span></button><button className="nav-button cinema-button" onClick={()=>s.patch({cinema:!s.cinema})}><Maximize2 size={14}/><span>{s.cinema?'Exit cinema':'Cinema'}</span><kbd>C</kbd></button></nav></header>
    <div className="intro"><div className="eyebrow"><span className="specimen-square"/> DIGITAL ENTOMOLOGY / SPECIMEN 001</div><h1>MOSQUITO<span className="title-period">.</span></h1><p>The internet gets on her nerves.</p><div className="intro-rule"/><div className="intro-note">A tiny creature.<br/>An impossibly noisy world.</div></div>
    <aside className="telemetry" aria-label="Organism telemetry"><div className="section-label"><span className="status-dot"/> HER CURRENT STATE</div><div className="behavior-line"><h2>{s.paused?'Paused':s.behavior.charAt(0).toUpperCase()+s.behavior.slice(1)}</h2><span className="behavior-icon"><Activity size={19}/></span></div><p className="behavior-copy">{s.paused?'A moment of stillness.':behaviorText[s.behavior]}</p>
      <div className="activity-heading"><span>NEURAL ACTIVITY</span><span className="activity-value">{(activity*100).toFixed(1)}<small>%</small></span></div><svg className="activity-chart" viewBox="0 0 218 42" role="img" aria-label="Recent simulated neural activity"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#79d8bd" stopOpacity=".16"/><stop offset="100%" stopColor="#79d8bd" stopOpacity="0"/></linearGradient></defs><path d={`M0,40 L${chart.replaceAll(' ',' L')} L216,40 Z`} fill="url(#chart-fill)"/><polyline points={chart} fill="none" stroke="#8dceb7" strokeWidth="1.25"/><line x1="0" y1="40" x2="218" y2="40" stroke="#253634" strokeDasharray="2 5"/></svg>
      <div className="telemetry-foot"><span>{Math.round(s.spikeRate).toLocaleString()} spikes / s</span><span>LOCAL SIM</span></div>
      <button className="inspect-link" onClick={()=>s.patch({drawer:'inspector'})}>Look inside her head <ArrowUpRight size={14}/></button>
    </aside>
    <div className="brain-annotation"><div className="annotation-dot"/><span>NEURAL PROJECTION</span><small>{s.graph?.count.toLocaleString()||'…'} neurons / synthetic network</small><div className="annotation-line"/></div>
    <div className="body-annotation"><span className="annotation-line"/><div><span>01 — THE ORGANISM</span><small>Six legs. One very sensitive disposition.</small></div></div>
    <div className="right-scale"><span>NEURAL</span><div/><span>SOMATIC</span></div>
    {selected!==null&&<div className="region-tooltip"><span className="status-dot"/>{MODULES[selected].name}<strong>{(s.modules[selected]*100).toFixed(1)}%</strong><small>{s.selectedModule===selected?'Selected pathways':'Click to trace pathways'}</small></div>}
    {s.follow&&<div className="signal-trace"><span className="eyebrow">FOLLOWING THE LATEST SIGNAL</span><div>{['Sensory','Integration','Motor','Body'].map((name,i)=><span key={name} className={traceStages[i]?'lit':''}>{name}{i<3&&<ChevronRight size={12}/>}</span>)}</div><button onClick={()=>s.patch({follow:false})}>End trace ×</button></div>}
    <div className="scene-controls" role="group" aria-label="Camera views"><button aria-label="Full exhibit view" title="Full exhibit · 1" className={s.view==='exhibit'?'active':''} onClick={()=>s.patch({view:'exhibit'})}><Orbit size={16}/><span>Exhibit</span></button><button aria-label="Brain detail view" title="Brain detail · 2" className={s.view==='brain'?'active':''} onClick={()=>s.patch({view:'brain'})}><Brain size={16}/><span>Brain</span></button><button aria-label="Body detail view" title="Body detail · 3" className={s.view==='body'?'active':''} onClick={()=>s.patch({view:'body'})}><Fingerprint size={16}/><span>Body</span></button><div className="control-divider"/><button aria-label="Toggle neural x-ray overlay" aria-pressed={s.xray} title="Neural x-ray" className={s.xray?'active':''} onClick={()=>s.patch({xray:!s.xray})}><Scan size={16}/></button><button aria-label="Reset camera" title="Reset camera · R" onClick={()=>s.patch({cameraReset:s.cameraReset+1})}><RotateCcw size={15}/></button></div>
    <div className="personality"><span>“</span>{s.caption}<span>”</span><i>— her, probably</i></div>
    <div className="interaction-hint">{s.tool==='lure'?<><Sun size={12}/> MOVE OR TOUCH THE STAGE TO PLACE WARMTH</>:<><MousePointer2 size={12}/> DRAG TO ORBIT <span>·</span> SCROLL TO EXPLORE</>}</div>
    <section className="bottom-region">
      <div className="event-strip"><div className="event-path"><span className={`source-tag ${source}`}>{source==='demo'?'SIMULATED':source.toUpperCase()}</span><span>{explained?descriptions[explained.kind]:'Listening to the world'}</span><ChevronRight size={12}/><span className="path-stage">{explained?.kind==='quiet'?'Neural decay':'Sensory burst'}</span><ChevronRight className="path-stage" size={12}/><span className="path-output">{s.paused?'Paused':s.behavior==='resting'?'Settling':s.behavior==='startled'?'Escape response':s.behavior==='sensing'?'Searching':'Motor activation'}</span></div><button onClick={()=>s.patch({follow:!s.follow})} className={s.follow?'active':''}>Follow signal <ArrowDownRight size={13}/></button></div>
      <div className="interaction-dock"><div className="dock-label"><span className="eyebrow">MAKE AN IMPRESSION</span><span>She’s listening.</span></div><div className="stimulus-buttons"><button disabled={s.paused} className={`stimulus-button lure ${s.tool==='lure'?'selected':''}`} onClick={()=>{s.patch({tool:s.tool==='lure'?'orbit':'lure'});if(s.tool!=='lure')manualStimulus('attraction');}} aria-pressed={s.tool==='lure'}><Sun/><span>Heat lure</span><kbd>L</kbd></button><button disabled={s.paused} className="stimulus-button" onClick={()=>manualStimulus('co2')}><Wind/><span>CO₂ puff</span><kbd>P</kbd></button><button disabled={s.paused} className="stimulus-button" onClick={tap}><CircleDot/><span>{tapNotice?'Give her a moment':'Tap the glass'}</span><kbd>G</kbd></button><button disabled={s.paused} className="stimulus-button shadow-button" onClick={()=>manualStimulus('shadow')}><Waves/><span>Passing shadow</span><kbd>S</kbd></button></div><div className="dock-transport"><button aria-label={s.paused?'Resume simulation':'Pause simulation'} title="Pause / resume · Space" className={`transport-button ${s.paused?'active':''}`} onClick={()=>s.patch({paused:!s.paused})}>{s.paused?<Play size={17}/>:<Pause size={17}/>}</button><button aria-label="Open inspector and settings" title="Inspector & settings" className="transport-button" onClick={()=>s.patch({drawer:'inspector'})}><SlidersHorizontal size={17}/></button></div></div>
      <footer><div className="feed-status"><span className={`status-dot ${s.feed.mode==='demo'?'amber':''}`}/><span className="feed-provider">{s.feed.mode==='demo'?'DEMO':'COINBASE'}</span><span className="feed-divider">/</span><div className="product-select"><select aria-label="Market product" value={s.product} onChange={e=>s.patch({product:e.target.value as typeof s.product})}><option>BTC-USD</option><option>ETH-USD</option></select><ChevronDown size={10}/></div><span className="connection-label" title={s.feed.reason}>{s.feed.mode==='demo'?(s.feed.state==='DEMO'?'SIMULATED INPUT':s.feed.state):s.feed.warmup?'WARMING UP':s.feed.state}</span><span className="event-age" title={s.feed.reason}>{s.feed.mode==='live'?(age!==null?`${age}s since trade${heartbeat?' · ♥':''}`:'awaiting trade'):s.feed.state==='DEMO'?'36s scenario':s.feed.state==='LIVE'?'Heartbeat healthy · awaiting trade':s.feed.state==='RECONNECTING'||s.feed.state==='STALE'?s.feed.reason:'Connecting to live feed'}</span></div><span className="truth-note">An artistic neural simulation driven by live data; not a biological reconstruction.</span><button className="footer-note" onClick={()=>s.patch({drawer:'about'})}>ABOUT THIS SPECIMEN <ArrowUpRight size={11}/></button></footer>
    </section>
    <div className="mobile-status"><span className="status-dot"/>{s.paused?'PAUSED':s.behavior.toUpperCase()}<span>{s.tool==='lure'?'TOUCH TO PLACE WARMTH':`${(activity*100).toFixed(1)}% ACTIVE`}</span></div>
    {s.paused&&<div className="paused-label"><Pause size={12}/> PAUSED <span>Incoming stimuli are discarded</span></div>}
    {!s.ready&&<div className="loading-label"><Circle className="loading-ring" size={18}/><span>Assembling a small nervous system…</span></div>}
    <div className="cinema-exit"><button onClick={()=>s.patch({cinema:false})}><Focus size={15}/> Exit cinema <kbd>C</kbd></button><button aria-label={s.paused?'Resume simulation':'Pause simulation'} onClick={()=>s.patch({paused:!s.paused})}>{s.paused?<Play size={15}/>:<Pause size={15}/>}</button><span>{s.feed.mode==='demo'?'DEMO':s.feed.state}</span></div>
    <Drawer/>
  </div>;
}
